### PR TITLE
direct hotfix xd

### PR DESCRIPTION
**Pull request by Skylocc**

### CODE REVIEW

**Comment by tsunyoku** [comment]
can you fix the indentation on the web request? its indented too many times so it’s making the request over every argument rather than just once

**Comment by Skylocc** [comment]
fixed xd

**Comment by tsunyoku** [comment]
no andshdjsndndns check discord

**Comment by Skylocc** [comment]
j

**Comment by tsunyoku** [comment]
works and seems good for now, will merge and probably re-do in the near future

**Pull request merged**
