### PR TITLE
Minor improvements (speed, better logging)

### PR DESCRIPTION
**Pull request by atteure**

### CODE REVIEW

**Comment by tsunyoku** [comment]
do you have any other optimisations you’d like to include before i merge or is this all?

**Comment by atteure** [comment]
don't think so, if there are i'll make a pr in a few days when i have more to contrib

**Comment by tsunyoku** [comment]
for speed and optimisations id rather not make constant prs for very basic things like this

i’ll merge this pr but in the future please only pr major changes, for things as small as this just tag me in the discord and i’ll add it myself just for organisation sake

**Comment by atteure** [comment]
sry u just told me to make prs whenever i wanna add anything lol but will do

**Comment by tsunyoku** [comment]
yea all good, just don’t bother for changes as tiny as these

**Pull request merged**
