### PR TITLE
temp fix for countries lol

### PR DESCRIPTION
**Pull request by Skylocc**

### CODE REVIEW

**Comment by tsunyoku** [comment]
if there is no country, then surely we should just deny the login request? is there ever a legitimate case where the country may be done for a non-malicious reason?

opinions valued :p

**Comment by atteure** [comment]
the problem isn't that they are failing to be assigned a country, the geoloc itself isn't working properly
i don't think this would fix anything and i agree with james

**Comment by tsunyoku** [comment]
we’ve discussed in dms and it’s a bit cursed:

iteki’s gulag instance uses the same process for countries & geoloc yet he can login just fine there, but not on asahi. i assume i have potentially fucked something up with grabbing the country from the request ip so i’ll investigate tomorrow.

thanks everyone!

**Comment by atteure** [comment]
# btw X-Real-IP is deprecated and is prone to attacks, reminder to use X-Forwarded-For instead

**Comment by tsunyoku** [comment]
alright cheers, will switch the header today and close the pr :p

**Comment by tsunyoku** [comment]
fixed in commit: https://github.com/tsunyoku/Asahi/commit/0d796a4099acabe37cdcc5ccca4aa3de3612384a

**Pull request closed without merging**
